---
plugins:
  stylelint-csstree-validator
rules:
  at-rule-name-case: lower
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  block-closing-brace-newline-after: never-single-line
  block-closing-brace-newline-before: always
  block-no-empty: true
  block-opening-brace-newline-after: always
  block-opening-brace-space-before: always
  color-hex-case: lower
  declaration-block-no-duplicate-properties: true
  declaration-block-semicolon-newline-after: always
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  function-comma-space-after: always
  function-parentheses-space-inside: never
  indentation: 2
  max-empty-lines: 1
  max-nesting-depth: 3
  media-feature-name-no-vendor-prefix: true
  no-duplicate-selectors: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-unknown-animations: true
  property-no-vendor-prefix: true
# list-comma-space-after: always
  selector-type-no-unknown: true
  string-quotes: single
  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  selector-max-specificity: "0,5,0"
# selector-no-id: true
  declaration-block-no-redundant-longhand-properties: [true, {ignoreShorthands: ["/grid-/"]}]
# declaration-block-no-ignored-properties: true
# selector-no-universal: true
# selector-no-type: [true, {ignore: ['descendant']}]
  selector-no-qualifying-type: true
  no-missing-end-of-source-newline: true
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  # no-empty-first-line: true
  # function-call-no-invalid: true

#  selector-no-combinator: true
#  selector-nested-pattern: '^[:>+~]+$'
#  no-indistinguishable-colors: true
# no-unsupported-browser-features: [true, {browsers: "last 2 versions, ie>=11", ignore: ['font-unicode-range', 'flexbox', 'viewport-units', 'css3-cursors-newer', 'outline']}]
#  csstree/validator: true

